= {project_name}
:navtitle: home
:page-layout: home-project
:!numbered:
:stem: latexmath


Introduction:: xref::attachment$lecture-rbobm-beamer-l1-2024.pdf[Notes > pdf]
Ingredients:: xref::attachment$lecture-rbobm-beamer-notations.pdf[Notes > pdf] 
Reduced Basis:: xref::attachment$lecture-rbobm-beamer-approx.pdf[Notes > pdf] 
//A priori::  xref::attachment$lecture-rbobm-beamer-apriori.pdf[Notes > pdf] 
//Error Bounds:: TODO
Extension to Non Compliant problems:: xref::attachment$lecture-rbobm-beamer-l4.pdf[Notes > pdf] 
Extension to Parabolic problems(time dependent problems):: xref::attachment$lecture-rbobm-beamer-parabolic.pdf[Notes > pdf] 
Extension to Non-affine  problems:: xref::attachment$lecture-rbobm-beamer-non-affine.pdf[Notes > pdf]
//
Homework 1:: xref::attachment$problem-set-1.pdf[> Homework 1 2024]
TP assimilation::  xref:tps/tp-assim-1.adoc[The Kalman Filter]
Homework 2:: xref::homework-2024/problem-set-2.adoc[> Homework 2 2024], xref::attachment$homework-2024-data.zip[> data]

